# Generated by Django 3.0.6 on 2020-07-22 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, default=uuid.uuid4, max_length=50, unique=True)),
                ('disabled', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referal_link', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralHit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('authenticated', models.BooleanField(help_text='Whether the hit was created by an authenticated user.')),
                ('ip', models.GenericIPAddressField(help_text='IP address at hit time')),
                ('user_agent', models.TextField(blank=True, help_text='User-Agent at hit time')),
                ('http_referer', models.TextField(blank=True, help_text='Referer header at hit time')),
                ('next', models.URLField(blank=True, help_text='The ?next parameter when the link was hit.')),
                ('confirmed', models.DateTimeField(blank=True, db_index=True, help_text='If set, the datetime at which the hit was marked as a successful referral.', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hit_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('referral_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='gift_ref.ReferralLink')),
            ],
        ),
    ]
