# Generated by Django 3.0.6 on 2020-06-08 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Time'),
        ),
    ]
