# Generated by Django 3.0.6 on 2020-07-24 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0003_confirmimage_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftingAndRecieving',
            fields=[
                ('withdrwal_frequency', models.PositiveSmallIntegerField(choices=[(1, 'first withdrawal'), (2, 'second withdrawal'), (3, 'recieving one'), (4, 'recieving two'), (5, 'recieving three'), (6, 'recieving four'), (7, 'recieving five')], verbose_name='Withdraw Frequecy')),
                ('username', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
